### ISSUE TITLE
The "search" button doesn't work on the landing page

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare-client#11]
Error in the javascript console : "TypeError: facet.hasValues is not a function".

**Comment by annelhote** [comment]
Bug reproduced in prod and in local.

**Comment by annelhote** [comment]
See commit https://github.com/ICIJ/datashare-client/commit/f8537a8454c7ac0f6e3b444dd31dd42136d4ac9b

**Comment by bamthomas** [comment]
I think that the problem of calling facet.hasValues() is linked to the persistent store (with local storage). What is persisted is probably the structure of the objects but not the prototype functions.
