### ISSUE TITLE
Named Entity Facets become empty after value selection

### ISSUE THREAD

**Issue by Julm** [ICIJ/datashare-client#12]
When one selects a value V in any named entity facet (Person, Organization, Location), 
the facet become empty, instead of displaying V. 

Actually, all named entity facets are emptied.

**Comment by annelhote** [comment]
To complete this issue, the results list should be filtered by the named entity once selected.

**Comment by annelhote** [comment]
3. Last (hopefully), select a named entity, invert it. The named entity is duplicated in the facet list results.

**Comment by annelhote** [comment]
How to test it :
1. Go on datashare
2. Reset all filters
3. Click on a Named entity
=> Check that the others Named Entity facets are filtered according to the selected Named Entity.
=> Check that the document results are filtered according to the selected Named Entity.
4. Click on "Invert" on this Named Entity
=> Check that this Named Entity appears only once in this list, at the first rank.

**Comment by Julm** [comment]
The initial issue is solved; meaning that it works when one value from one Named entity facet, say a Person, is selected.

But as soon as one selects a second value from another facet, say Organization, then only the second value is displayed and all other values from all other Named Entity facets are emptied (Person, Location). 

See attached screenshots.
![screenshot from 2018-11-06 17-56-13](https://user-images.githubusercontent.com/2683717/48081209-cc8c9a00-e1ef-11e8-9450-7eea1ced9935.png)
![screenshot from 2018-11-06 17-56-01](https://user-images.githubusercontent.com/2683717/48081210-cd253080-e1ef-11e8-81d4-ba44b75f02d0.png)

**Comment by annelhote** [comment]
Ooooooh. Thank you @Julm for this feedback ! I'll take it in charge soon.

**Comment by annelhote** [comment]
@Julm Should be ok for testing.

**Comment by annelhote** [comment]
About facets, I found this other bugs #16  and #17.

**Comment by Julm** [comment]
It does work! Thanks @annelhote
