### ISSUE TITLE
My Path facet does not display any value

### ISSUE THREAD

**Issue by Julm** [ICIJ/datashare-client#13]
Although there is one directory in my (jmartin) personal folder on datashare.cloud.icij.org

**Comment by annelhote** [comment]
@Julm Let's try a quick fix :
- In your browser, logout from datashare-1.cloud.icij.org
- Connect to datashare-1 through SSH
- Delete your own ES index
`curl -X DELETE localhost:9200/INDEX`
- In your browser, login to datashare-1.cloud.icij.org
- Reindex your files
=> Let me know if you still have the same issue
