### ISSUE TITLE
Fake worker error when I try to preview a PDF

### ISSUE THREAD

**Issue by chriszs** [ICIJ/datashare-client#24]
When I click the "Preview" tab on a PDF entry while using 2.0 I get an error that says:
> Setting up fake worker failed: "Cannot read property 'setup' of undefined".

My console shows a 404 error for /static/js/pdf.worker.js

This happens both on my Mac and a cloud deployment while using Chrome.

**Comment by pirhoo** [comment]
Hi @chriszs, thanks for reporting this. We'll have a look soon!

**Comment by chriszs** [comment]
This appears to be fixed in 3.1.

**Comment by pirhoo** [comment]
Looks like it's fixed indeed! It's a build problem, we'll do another check before closing the issue. Thanks!

**Comment by pirhoo** [comment]
All good for us, thanks @chriszs!
