### ISSUE TITLE
client only showing 8 folders in path filter 

### ISSUE THREAD

**Issue by vincib** [ICIJ/datashare-client#99]
When filtering for paths in the search engine, vue is only showing 8 folders and can't show more.

Looks like it's in https://github.com/ICIJ/datashare-client/blob/master/src/utils/settings.js

I was able to push it to 20, but this requires a bit of hacking, by using the datashare.sh (whose -w options disappeared by the way) and using an nginx conf to proxyfie /api /settings and /version to the docker and serve the rest on our local copy of this repository built with "yarn build" 

Could it be possible to add this to some settings available through datashare.sh ? or in the web interface ? or just put it higher than 8? 

Thanks !

**Comment by pirhoo** [comment]
Hi Benjamin! I'm moving your issue to the main repository :) This is definitely not intentional, the path filter shouldn't be paginated. We'll fix that soon!

**Comment by annelhote** [comment]
Fixed in release 6.3.2.

**Comment by annelhote** [comment]
Just to let you know, the `-w` option has been replaced by the `-m` one. `m` stands for MODE and can be SERVER, LOCAL, NER, BATCH, EMBEDDED or CLI. CLI mode is the only one where the web server is not launched. Default value is LOCAL.

Hope this help.
